pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot\[bot\]$
      - check-success=Check
      - check-success=Format
      - check-success~=Test \(.*\)
    actions:
      merge:
        method: squash
