[package]
name = "youtube-extractor"
version = "0.1.0"
authors = ["Tilmann Meyer <allescrafterx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
chrono = "0.4.19"
regex = "1.4.5"
once_cell = "1.7.2"

[dependencies.async-std]
version = "1.9.0"
features = ["unstable", "tokio1", "attributes"]

[dependencies.reqwest]
version = "0.11.2"
features = ["cookies"]
