name: Audit
on:
  pull_request:
    paths:
      - Cargo.toml
  push:
    paths:
      - Cargo.toml
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  security_audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.3.4
      - name: Check | Audit
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
