name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  cargo:
    name: Publish Cargo Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build | Publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
  github:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup | Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.7"
      - name: Setup | Release notes
        run: |
          GO111MODULE=on go get github.com/git-chglog/git-chglog/cmd/git-chglog@0.14.2
          git-chglog -c .github/chglog/release.yml -o RELEASE.md $(git describe --tags)
      - name: Build | Publish
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
